stages:
  data_cleaning:
    cmd: python src/data/data_cleaning.py
    deps:
    - data/raw/songs_data.csv
    - src/data/data_cleaning.py
    outs:
    - data/cleaned/songs_cleaned_data.csv
  data_preprocessing:
    cmd: python src/features/data_preprocessing.py
    deps:
    - data/cleaned/songs_cleaned_data.csv
    - src/features/data_preprocessing.py
    outs:
    - data/processed/transformed_data.npz
    - models/preprocessor.joblib
